-- Functions
DROP FUNCTION IF EXISTS AVAILABILITY(DATE, DATE, INTEGER, INTEGER[]);
DROP FUNCTION IF EXISTS IIF(BOOLEAN, DATE, DATE);

-- Bookings
DROP TABLE IF EXISTS booking;
DROP TYPE IF EXISTS BookingStatus;
DROP TYPE IF EXISTS BookingMealPlan;

-- Rates
DROP TABLE IF EXISTS rate;

-- Rooms
DROP TABLE IF EXISTS room;
DROP FUNCTION IF EXISTS ROOM_ACCOMMODATION();

-- Guests
DROP TABLE IF EXISTS guest;
DROP TYPE IF EXISTS Gender;

-- Users
DROP TABLE IF EXISTS login;

